### ISSUE TITLE
X86 algorithm does not generate same outputs as X64 algorithm

### ISSUE THREAD

**Issue by J-Griffin** [darrenkopp/murmurhash-net#1]
With the same seed, the two algorithms do not generate the same hashes given the same input. Is this expected?

``` C#
// Example
var murmur86 = MurmurHash.Create128(0, true, AlgorithmPreference.X86);
var murmur64 = MurmurHash.Create128(0, true, AlgorithmPreference.X64);
byte[] data = Guid.NewGuid().ToByteArray();

// Assert fails
Assert.Equal(murmur86.ComputeHash(data), murmur64.ComputeHash(data));
```

I ran into this on accident because the default argument, AlgorithmPreference.Auto picks based on bitness of the application. I was generating hashes from two different applications against the same data store. One of those applications happened to be 32bit and the other 64.

**Comment by darrenkopp** [comment]
As far as i know, yes, but i may be wrong. The values I use to verify my implementation in MurmurHash.Specs come from [main.cpp from the original C++ source code](https://code.google.com/p/smhasher/source/browse/trunk/main.cpp), and there is a different value for X86 and X64.

**Comment by J-Griffin** [comment]
Alright, good to know. Might be worth mentioning in the readme.md. Given this, it's not super great to auto flip between two hashes that yield different results.
