### ISSUE TITLE
Benchmarks required

### ISSUE THREAD

**Issue by IhnatKlimchuk** [darrenkopp/murmurhash-net#7]
Does it make sense to add some benchmarks? That would be great to compare performance with another implementations.

**Comment by Belorus** [comment]
http://2.bp.blogspot.com/-xh2jFgCeDWk/UCSzLR8CdCI/AAAAAAAAAaw/ErL1wexLDq0/s1600/murmur3.png

**Comment by darrenkopp** [comment]
Woah, not sure why I never got notified about this issue, sorry about that. There's two projects that can run a basic benchmark already, but I should update to just use Benchmark.net.

https://github.com/darrenkopp/murmurhash-net/blob/master/Runners/Program.cs
