### ISSUE TITLE
same bytes different hash

### ISSUE THREAD

**Issue by maurosampietro** [darrenkopp/murmurhash-net#8]
i initialize MurMurHash with a fixed seed (131).
Different assemblies calling ComputeHash with a given array of bytes produce different hashes .
I double checked and i swear i'm sober :)

How is that possible?

**Comment by maurosampietro** [comment]
I was using anycpu compiling, anyway I forced x86 hash

**Comment by darrenkopp** [comment]
Whoops, sorry I didn't notice this issue until now! Sounds like you figured this out already, but yes the main downside of this algorithm is that the x86 version and x64 version of the 128-bit hash produce different values.
